<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'This is a string to translate!' => 'یہ ترجمہ کرنے کے لئے ایک تار ہے!',
    'This is another string to translate!' => 'یہ ترجمہ کرنے کے لئے ایک اور سٹرنگ ہے!',
    'Internationalization (I18N) refers to the process of designing a software application so that it can be adapted to various languages and regions without engineering changes. For Web applications, this is of particular importance because the potential users may be worldwide. Yii offers a full spectrum of I18N features that support message translation, view translation, date and number formatting.'=> 
    'عالمگیریت (i18n)، تا کہ یہ انجینئرنگ کی تبدیلی کے بغیر مختلف زبانوں اور علاقوں کے مطابق ڈھال لیا جا سکتا ہے ایک سافٹ ویئر کی درخواست کے ڈیزائن کے عمل سے مراد ہے. ویب اطلاقات کے لئے اس خاص اہمیت کا حامل ہے ممکنہ صارفین کو دنیا بھر میں ہو سکتا ہے کیونکہ. Yii ایک مکمل فراہم کرتا ہے ، بھجیں ترجمہ سپورٹ دیکھنے ترجمہ، تاریخ اور نمبر فارمیٹنگ کہ I18n کے خصوصیات میں سے سپیکٹرم.',
];
